global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['server:8000']  # ou autre port utilisé pour les métriques
  - job_name: 'celery'
    static_configs:
      - targets: ['server:5555']  # si tu exposes les métriques de celery

